services:

  backend:
    build: ./backend
    container_name: backend
    ports:
      - '8000:8000'

  ui:
    build: ./ui
    container_name: ui
    ports:
      - '3000:3000'

  nginx:
    build: ./nginx
    container_name: nginx
    depends_on:
      - backend
      - ui
    ports:
      - '80:80'